### ISSUE TITLE
Switch to tctildr

### ISSUE THREAD

**Issue by AndreasFuchsSIT** [tpm2-software/tpm2-totp#19]
Before next release, switch to tctildr as stated here: https://github.com/tpm2-software/tpm2-totp/pull/18#pullrequestreview-230217079

**Comment by diabonas** [comment]
See https://github.com/diabonas/tpm2-totp/tree/tss2-tctildr for a draft implementation based on the current state of development (https://github.com/flihp/tpm2-tss/commit/942c9d9015982cd251d095407d536fe6ef963e9b).
