### ISSUE TITLE
Password should never be passed as an argument

### ISSUE THREAD

**Issue by EvilBit** [tpm2-software/tpm2-totp#86]
Passing the password as an argument exposes it to other processes via `/proc` and constitutes a potential leak of this critical secret.

The password should only ever be passed via a file descriptor, possibly  `stdin` per default or if called interactively.

**Comment by diabonas** [comment]
Good point; probably the easiest way of achieving this would be accepting `-` as a special value to mean "read the password from stdin instead" (which means you cannot specify a literal dash `-` as a password any more directly as a command line argument, but I can live with that).
